version: "3.2"

services:
  api:
    build: ./api
    environment:
      - CONNECTION_STRING=postgres://osaid:osaid@db/demo_db
    networks:
      - network-backend
      - network-frontend

  web:
    build: ./web
    environment:
      - API_URL=http://api:3001/data
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - network-frontend

networks:
  network-backend:
  network-frontend:

