version: "3.2"

services:
  api:
    build: ./api
    environment:
      - CONNECTION_STRING=postgres://osaid:osaid@db/demo_db
    depends_on:
      - db
    networks:
      - network-backend
      - network-frontend

  web:
    build: ./web
    environment:
      - API_URL=http://api:3001/data
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - network-frontend

  db:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: osaid
      POSTGRES_PASSWORD: osaid
      POSTGRES_DB: demo_db
    volumes:
      - ./init_sql_scripts/:/docker-entrypoint-initdb.d
    networks:
      - network-backend

networks:
  network-backend:
  network-frontend: